language: go
go:
  - 1.12.5

env:
  - GO111MODULE=on

before_install:
  - go get -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)