version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pwd
    ports:
      - "5432:5432"
  api:
    restart: always
    depends_on:
      - "db"
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: server.dockerfile
